version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - "ows-auth-service-postgres:/var/lib/postgresql/data"

  auth-service-api:
    build: .
    command: yarn start
    volumes:
      - .:/ows-auth-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  ows-auth-service-postgres:
#  ows-auth-service-redis:
