version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - "ows-auth-service-postgres:/var/lib/postgresql/data"
#  redis:
#    image: redis:latest
#    volumes:
#      - "ows-auth-service-redis:/data"

  auth-service-api:
    build: .
    command: yarn start
    volumes:
      - .:/ows-auth-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
#      - redis

#  auth-service-job-queue:
#    build: .
#    command: bundle exec sidekiq
#    volumes:
#      - ".:/ows-auth-service"
#    depends_on:
#      - postgres
#      - redis
#    env_file:
#      - .env

volumes:
  ows-auth-service-postgres:
#  ows-auth-service-redis:
